### ISSUE TITLE
pom.xml is missing dependency information

### ISSUE THREAD

**Issue by gclayburg** [akquinet/vaangular#3]
when running 
```
mvn exec:java -Dexec.mainClass="de.akquinet.engineering.vaadin.vaangular.demo.VaangularApplication"
```

I get this error

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.004s
[INFO] Finished at: Mon Nov 21 11:37:35 MST 2016
[INFO] Final Memory: 13M/144M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project vaangular: Could not resolve dependencies for project de.akquinet.engineering.vaadin.vaangular:vaangular:jar:0.1.3-SNAPSHOT: Could not find artifact de.akquinet.engineering:javascriptplus-for-vaadin:jar:0.1.3-SNAPSHOT -> [Help 1]
```

Am I missing a repository definition maybe?

**Comment by sebastianrothbucher** [comment]
Hi Gary, thanks for reporting! I think running the ```mvn exec:java ...``` from within ```vaangular-demo``` will solve the issue. Due to Vaadin Directory constraints, I had to say goodbye to parent POMs which makes dependencies harder indeed. Anyways: I did update the description - would be great when you can try from vaangular-demo and report. Looking fw 2 that... Thanks again  Sebastian

**Comment by rlhLegoSoft** [comment]
Can you help me? I have the same problem. The pom.xml send me an error for the javascriptplus-for-vaadin artifact (missing articraft). I tried two version : 0.1.3-SNAPSHOT and 0.1.2. Neither one workes.

Any idea?

**Comment by rlhLegoSoft** [comment]
I solve the problem. It is a version problem: Us this articrafts version instead:
		<dependency>
			<groupId>de.akquinet.engineering.vaadin.vaangular</groupId>
			<artifactId>vaangular</artifactId>
			<version>0.1.2</version>
		</dependency>
       <dependency>
			<groupId>de.akquinet.engineering</groupId>
			<artifactId>javascriptplus-for-vaadin</artifactId>
			<version>0.1.2</version>
		</dependency>

**Comment by sebastianrothbucher** [comment]
Indeed, not including the parent pom will solve a lot - including this one.

**Comment by rlhLegoSoft** [comment]
Thanks, I just want to congratulate you. An excellent add-on. We have many developers with AngularJS experience and of course Vaadin experience. So we plan to use the best of both words (i.e, server and client development).

**Comment by sebastianrothbucher** [comment]
Thanks - and good luck!

**Comment by rlhLegoSoft** [comment]
Dear Sebastian, I had a problem when I try to run your add-on inside Liferay. The widget show correctly but when I want to communication between AngulaJS and Vaadin the "variables" Map is empty and send me a null pointer exception.
Maybe the error is  inside your JavaScript Plus add on. 

Any idea?

**Comment by rlhLegoSoft** [comment]
I solved !! After day and a half it was a stupid error: the "sliderPos" variable must be initialized. If not the getVariables().getVariable("sliderPos") returns null. Sorry for my stupidity.
Other issue: We want to send your add-on to production environment but we have a problem. When the liferay portlet is loaded, it delays more than 5 seconds (I believe is because all angular.js is loaded). Any idea how can I reduce this delay time (i.e., Vaadin takes 0.5 or less to load)

**Comment by OliverDamm** [comment]
I opened a new issue for the delay problem. this issue is closed.
